apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: parquimetro-app-hpa
  namespace: yurisena-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: parquimetro-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 80%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 70%
